#
# This tests the extension-ci-tools works as expected
#
name: Test CI Tools
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  extension-template-main:
    name: Extension template
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      extension_name: quack
      override_repository: duckdb/extension-template
      override_ref: main
      duckdb_version: v1.3.2
      override_ci_tools_repository: ${{ github.repository }}
      ci_tools_version: ${{ github.sha }}
      extra_toolchains: 'parser_tools;fortran;omp;go;python3;downgraded_aws_cli;'
      save_cache: ${{ github.event_name != 'pull_request' }}
      vcpkg_binary_sources: ${{ github.event_name == 'push' && vars.VCPKG_BINARY_SOURCES || '' }}
      upload_all_extensions: true
      extra_extension_config: |
        duckdb_extension_load(json)
        duckdb_extension_load(tpch)
    secrets: inherit